name: markopalski
favicon: null
layout_spectrum: 0.10298496810719371
typography_spectrum: 0.8224684323649853
title: Selected works
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.054060172755271196
  lightness: 0.6870342227630317
  saturation: 0.11127063049934804
  rhythmicContrast: 0.33464919426478446
purpose: []
