name: Mark Opalski UX
favicon: null
layout_spectrum: 0.38767
typography_spectrum: 0.31334
title: 'Specializing in the Design of User Experience and Interaction Design. '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#64dbfe'
    - '#004a97'
    - '#01b7f9'
    - '#942e65'
    - '#fd7041'
  brandStrength: 0.9375
  lightness: 0.0625
  saturation: 0.11127063049934804
  rhythmicContrast: 0.75
purpose: []
